# Generated by Django 4.2 on 2024-04-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='HSBCQuestions',
        ),
    ]
