# Generated by Django 4.2 on 2024-04-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_hsbcquestions_techmquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
