# Generated by Django 4.2 on 2024-03-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_questionstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('heading', models.TextField(default=True)),
                ('Description', models.TextField(default=True)),
            ],
        ),
    ]
