# Generated by Django 5.0.3 on 2024-04-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0003_alter_contactmessage_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
