# Generated by Django 4.2 on 2024-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_alter_contactmessage_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstable',
            name='Q_type',
            field=models.TextField(default=True),
        ),
    ]
