# Generated by Django 4.2 on 2024-04-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_hsbctquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsbctquestions',
            name='q_type',
            field=models.TextField(default=True),
        ),
    ]
