# Generated by Django 4.2 on 2024-04-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0006_hsbctquestions_q_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSBCTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QId', models.CharField(max_length=25, unique=True)),
                ('Question', models.TextField(default=True)),
                ('Option1', models.TextField(default=True)),
                ('Option2', models.TextField(default=True)),
                ('Option3', models.TextField(default=True)),
                ('Option4', models.TextField(default=True)),
                ('Answer', models.TextField(default=True)),
                ('q_type', models.TextField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HSBCTQuestions',
        ),
    ]
