# Generated by Django 5.0.2 on 2024-04-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_questionhsbc'),
        ('auth_module', '0008_questionhsbc_delete_hsbctquestion'),
    ]

    operations = [
    ]
