# Generated by Django 4.2 on 2024-04-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0010_contactmessage_delete_questionhsbc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
